export const allDisease = [
    { name: "Common Cold" },
    { name: "Influenza (Flu)" },
    { name: "Gastroenteritis (Stomach Flu)" },
    { name: "Pneumonia" },
    { name: "Tuberculosis (TB)" },
    { name: "HIV/AIDS" },
    { name: "Hepatitis (A, B, C)" },
    { name: "Chickenpox" },
    { name: "Herpes Simplex Virus (HSV)" },
    { name: "Lyme Disease" },
    { name: "Meningitis" },
    { name: "Syphilis" },
    { name: "Malaria" },
    { name: "COVID-19" },
    { name: "Diabetes Mellitus (Type 1, Type 2)" },
    { name: "Hypertension (High Blood Pressure)" },
    { name: "Asthma" },
    { name: "Chronic Obstructive Pulmonary Disease (COPD)" },
    { name: "Heart Disease (e.g., Coronary Artery Disease, Congestive Heart Failure)" },
    { name: "Cancer (e.g., Breast, Lung, Prostate, Colon)" },
    { name: "Osteoarthritis" },
    { name: "Rheumatoid Arthritis" },
    { name: "Stroke" },
    { name: "Systemic Lupus Erythematosus (SLE)" },
    { name: "Multiple Sclerosis (MS)" },
    { name: "Hashimoto's Thyroiditis" },
    { name: "Graves' Disease" },
    { name: "Celiac Disease" },
    { name: "Psoriasis" },
    { name: "Depression" },
    { name: "Anxiety Disorders (e.g., Generalized Anxiety Disorder, Panic Disorder)" },
    { name: "Bipolar Disorder" },
    { name: "Schizophrenia" },
    { name: "Obsessive-Compulsive Disorder (OCD)" },
    { name: "Post-Traumatic Stress Disorder (PTSD)" },
    { name: "Irritable Bowel Syndrome (IBS)" },
    { name: "Gastroesophageal Reflux Disease (GERD)" },
    { name: "Peptic Ulcer Disease" },
    { name: "Crohn’s Disease" },
    { name: "Ulcerative Colitis" },
    { name: "Gallstones" },
    { name: "Lactose Intolerance" },
    { name: "Migraine" },
    { name: "Epilepsy" },
    { name: "Parkinson's Disease" },
    { name: "Alzheimer’s Disease" },
    { name: "Neuropathy" },
    { name: "Hypothyroidism" },
    { name: "Hyperthyroidism" },
    { name: "Addison's Disease" },
    { name: "Cushing's Syndrome" },
    { name: "Urinary Tract Infection (UTI)" },
    { name: "Kidney Stones" },
    { name: "Prostate Disorders (e.g., Benign Prostatic Hyperplasia)" },
    { name: "Menstrual Disorders (e.g., Endometriosis, Polycystic Ovary Syndrome)" },
    { name: "Osteoporosis" },
    { name: "Fibromyalgia" },
    { name: "Gout" },
    { name: "Anemia" },
    { name: "Hemophilia" },
    { name: "Sickle Cell Disease" },
    { name: "Leukemia" },
];
