// src/data/symptomsData.js
export const allSymptoms = [
  { name: 'Fever' },
    { name: 'Blocked nose' },
    { name: 'Cough' },
    { name: 'Runny nose' },
    { name: 'Throat pain' },
    { name: 'Headache' },
    { name: 'Loose motion' },
    { name: 'Constipation' },
    { name: 'Gas' },
    { name: 'Vomiting/nausea' },
    { name: 'High cholesterol' },
    { name: 'Diabetes' },
    { name: 'High BP' },
    { name: 'Low BP' },
    { name: 'Back pain' },
    { name: 'Migraine' },
    { name: 'Acne' },
    { name: 'Hairfall' },
    { name: 'Dry skin' },
    { name: 'Obesity' },
    { name: 'Abdominal pain' },
    { name: 'Rashes' },
    { name: 'Back-pain' },
    { name: 'Period-related issues' },
    { name: 'Erectile dysfunction' },
    { name: 'Period-related issue' },
    { name: 'Pregnancy related issue' },
    { name: 'Breast scan' },
    { name: 'Excessive bleeding' },
    { name: 'Bleeding after sex' },
    { name: 'Vomiting/nausea' },
    { name: 'Thyroid problems' },
    { name: 'Pimples/acne' },
    { name: 'Reddish skin' },
    { name: 'Rashes' },
    { name: 'Spots on skin' },
    { name: 'Itching' },
    { name: 'Dark circles' },
    { name: 'Hairfall' },
    { name: 'Dry scalp/dandruff' },
    { name: 'Back pain' },
    { name: 'Neck pain' },
    { name: 'Lower back pain' },
    { name: 'Elbow pain' },
    { name: 'Joint pains' },
    { name: 'Sprain' },
    { name: 'Arthritis' },
    { name: 'Heel pain' },
    { name: 'Fracture' },
    { name: 'Left knee pain' },
    { name: 'Right knee pain' },
    { name: 'Left shoulder pain' },
    { name: 'Right shoulder pain' },
    { name: 'Wrist injury' },
    { name: 'Back injury' },
    { name: 'Hand injury' },
    { name: 'Shoulder injury' },
    { name: 'Neck injury' },
    { name: 'Elbow injury' },
    { name: 'Knee injury' },
    { name: 'Hip injury' },
    { name: 'Return to play' },
    { name: 'Foot injury' },
    { name: 'Shin splints' },
    { name: 'Ligament tear' },
    { name: 'Achilles tendon injury' },
    { name: 'Joint dislocation' },
    { name: 'Groin pull' },
    { name: 'Hamstring injuries' },
    { name: 'Muscle strain' },
    { name: 'Workout injuries' },
    { name: 'Footwear related queries' },
    { name: 'Chest pain' },
    { name: 'Bypass surgery' },
    { name: 'Pacemaker implantation' },
    { name: 'Angiography' },
    { name: 'Irregular heartbeat' },
    { name: 'Slow heart rate' },
    { name: 'Giddiness' },
    { name: 'Pounding heart beat' },
    { name: 'Repeated miscarriages' },
    { name: 'IVF related query' },
    { name: 'Tubal block' },
    { name: 'IUI related query' },
    { name: 'Hernia' },
    { name: 'Testicular pain' },
    { name: 'Varicose veins' },
    { name: 'Ulcer' },
    { name: 'Swelling' },
    { name: 'Spine problems' },
    { name: 'AV malformations' },
    { name: 'Brain bleeding' },
    { name: 'Epilepsy surgery' },
    { name: 'Brain tumor' },
    { name: 'Head and neck tumors' },
    { name: 'Lung cancer' },
    { name: 'Gastrointestinal cancer' },
    { name: 'Urogenital cancer' },
    { name: 'Spinal tumors' },
    { name: 'Blood cancer' },
    { name: 'Skin cancer' },
    { name: 'Bone and muscle cancer' },
    { name: 'Endocrine cancer' },
    { name: 'Breast and gynaecological problems' },
    { name: 'Chemotherapy related queries' },
    { name: 'Renal cancer' },
    { name: 'Prostate problems' },
    { name: 'Urinary stream issues' },
    { name: 'Urinary bladder problems' },
    { name: 'Frequent urinary tract infections' },
    { name: 'Kidney and ureteric stones' },
    { name: 'Chronic cough' },
    { name: 'Sleep apnea' },
    { name: 'Tuberculosis' },
    { name: 'Breathlessness (chronic)' },
    { name: 'Bronchiectasis' },
    { name: 'COPD' },
    { name: 'Asthma' },
    { name: 'Sleep disorders' },
    { name: 'Structural abnormalities of lung' },
    { name: 'Smoking deaddiction advice' },
    { name: 'Acute Renal Failure' },
    { name: 'Chronic kidney disease' },
    { name: 'Glomerulonephritis' },
    { name: 'Polycystic kidney' },
    { name: 'Renal transplant related query' },
    { name: 'Fluctuating Blood Sugars' },
    { name: 'Insulin related concerns' },
    { name: 'Oral antidiabetic medications' },
    { name: 'Diabetic ulcers' },
    { name: 'Nerve issue related to diabetes' },
    { name: 'Kidney related issues in diabetes' },
    { name: 'Infections in diabetes' },
    { name: 'Thyroid Disorders' },
    { name: 'Pituitary disorders' },
    { name: 'Adrenal disorders' },
    { name: 'Ovarian disorders' },
    { name: 'Testicular disorders' },
    { name: 'Pancreatic disorders' },
    { name: 'Growth related disorders' },
    { name: 'Ear Discharge' },
    { name: 'Ear pain' },
    { name: 'Mouth breathing' },
    { name: 'Ringing in ears' },
    { name: 'Swelling over the neck' },
    { name: 'Ear congestion' },
    { name: 'Hearing aids' },
    { name: 'Hearing loss' },
    { name: 'Pain in abdomen' },
    { name: 'Bleeding of digestive tract' },
    { name: 'Constipation' },
    { name: 'Loose stools' },
    { name: 'Heartburn/indigestion' },
    { name: 'Bloody vomit' },
    { name: 'Jaundice' },
    { name: 'Abdominal distention' },
    { name: 'Bloody stool' },
    { name: 'Seizure' },
    { name: 'Weakness of limb' },
    { name: 'Neck pain' },
    { name: 'Loss of balance' },
    { name: 'Memory loss' },
    { name: 'Loss of consciousness' },
    { name: 'Shivering' },
    { name: 'Delayed milestones' },
    { name: 'Cleft lip' },
    { name: 'Learning disability' },
    { name: 'Mental retardation' },
    { name: 'Pain Ejaculation' },
    { name: 'Premature ejaculation' },
    { name: 'Erectile dysfunction' },
    { name: 'Decreased sexual drive' },
    { name: 'Depression' },
    { name: 'Anxiety' },
    { name: 'Obsessive compulsive disorder' },
    { name: 'Stress' },
    { name: 'Tooth sensitivity' },
    { name: 'Missing teeth' },
    { name: 'Jaw pain' },
    { name: 'Toothache' },
    { name: 'Dental caries' },
    { name: 'Red and bleeding gums' },
    { name: 'Tooth discolouration' },
    { name: 'Crooked teeth' },
    { name: 'Black gums' },
    { name: 'Swollen gums' },
    { name: 'Stiff joints' },
    { name: 'Joint swelling' },
    { name: 'Redness over the joint' },
    { name: 'Vasculitis' },
    { name: 'Redness of eyes' },
    { name: 'Itching of eyes' },
    { name: 'Discharge from eye' },
    { name: 'Watering of eyes' },
    { name: 'Non-specific pain' },
    { name: 'Shoulder pain' },
    { name: 'Knee pain' },
    { name: 'Neck pain' },
    { name: 'Elbow pain' },
    { name: 'Ankle pain' },
    { name: 'Wrist pain' }
];
