// vaccineData.js
export const vaccineData = [
    { name: "DTP (Diphtheria, Tetanus, Pertussis)", description: "Diphtheria, Tetanus, Whooping Cough" },
    { name: "IPV (Inactivated Polio Vaccine)", description: "Polio" },
    { name: "MMR (Measles, Mumps, Rubella)", description: "Measles, Mumps, Rubella" },
    { name: "BCG (Bacillus Calmette-Guérin)", description: "Tuberculosis" },
    { name: "Hib (Haemophilus influenzae type b)", description: "Hib Disease" },
    { name: "Hepatitis B", description: "Hepatitis B" },
    { name: "Rotavirus", description: "Rotavirus Gastroenteritis" },
    { name: "PCV (Pneumococcal Conjugate Vaccine)", description: "Pneumonia, Pneumococcal Diseases" },
    { name: "Typhoid", description: "Typhoid Fever" },
    { name: "Hepatitis A", description: "Hepatitis A" },
    { name: "Japanese Encephalitis", description: "Japanese Encephalitis" },
    { name: "Influenza (Flu)", description: "Influenza" },
    { name: "HPV (Human Papillomavirus)", description: "HPV Infection (for older children)" },
    { name: "Pfizer-BioNTech COVID-19 Vaccine", description: "COVID-19" },
    { name: "Moderna COVID-19 Vaccine", description: "COVID-19" },
    { name: "Covishield (AstraZeneca)", description: "COVID-19" },
    { name: "Covaxin (Bharat Biotech)", description: "COVID-19" },
    { name: "Sputnik V", description: "COVID-19" },
    { name: "Novavax (Nuvaxovid)", description: "COVID-19" },
    { name: "Hepatitis A", description: "Hepatitis A" },
    { name: "Typhoid", description: "Typhoid Fever" },
    { name: "Cholera", description: "Cholera" },
    { name: "Yellow Fever", description: "Yellow Fever" },
    { name: "Japanese Encephalitis", description: "Japanese Encephalitis" },
    { name: "Pneumococcal", description: "Pneumonia" },
    { name: "Influenza (Flu)", description: "Influenza" },
    { name: "Human Papillomavirus (HPV)", description: "HPV Infection" },
    { name: "Smallpox (when necessary)", description: "Smallpox" },
    { name: "MenACWY (Meningococcal)", description: "Meningococcal Disease" },
    { name: "MenB (Meningococcal B)", description: "Meningococcal B Disease" },
    { name: "Cervarix", description: "Cervical Cancer (HPV-related)" },
    { name: "Gardasil", description: "Cervical Cancer (HPV-related)" },
    { name: "BioNTech's mRNA vaccines (various candidates)", description: "Various infectious diseases (experimental)" },
    { name: "Various viral vector vaccines (experimental)", description: "Various infectious diseases (experimental)" }
  ];
  